@startuml Restaurant (POST)

header Restaurant_Reservation
footer Page %page% of %lastpage%
title "Post a restaurant (POST)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:restaurants" as routerRestaurants
participant "<<middleware>>\n:auth" as middlewareAuth
participant "<<controllers>>\n:restaurants" as controllersRestaurants
participant "<<model>>\n:Restaurant" as modelRestaurant
database "<<MongoDB>>\n:restaurants" as RestaurantsDatabase

client->server ++:req.post('/restaurants')
server->routerRestaurants ++:app.use('/restautants',restaurants)
routerRestaurants -> middlewareAuth ++:protect(req,res,next)
middlewareAuth -> middlewareAuth ++:authorize('admin')
middlewareAuth -> routerRestaurants --: next()
routerRestaurants -> controllersRestaurants ++:createRestaurant()
controllersRestaurants->modelRestaurant ++:create(req.body)
modelRestaurant ->RestaurantsDatabase ++: RestaurantSchema
RestaurantsDatabase --> modelRestaurant --: restaurant
modelRestaurant-->controllersRestaurants --:restaurant
controllersRestaurants->client --:response

@enduml
